version: '3.9'

services:
  api:
    build: ./api/
    volumes:
      - ${PWD}/api:/usr/src/api:Z
      - ${PWD}/data:/usr/src/api/data:Z
    ports:
      - 8000:8000
    network_mode: host
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - postgres.env
    environment:
      TZ: 'America/Mexico_City'
      PGTZ: 'America/Mexico_City'

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U topol -d logs"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:Z
    env_file:
      - postgres.env
    environment:
      TZ: 'America/Mexico_City'
      PGTZ: 'America/Mexico_City'

